try:
  a=1+'hundred'
  b=2/0
except Exception as e:
  print('error:',e)  
  
  #test_1가 다른 결과가 나온다.
